name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install sdl
      run: sudo apt install libsdl2-dev libsdl2-2.0-0 -y
    - name: make
      run: make
