name: MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_MacOS:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install_dependencies
      run: | 
        brew install SDL2
    - name: make
      run: make
